#############################################################################
# Makefile for building: MocpInterface
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sun Apr 7 20:35:10 2013
# Project:  MocpInterface.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.4/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ -o Makefile MocpInterface.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.4/include/QtCore -I/usr/local/Trolltech/Qt-4.8.4/include/QtGui -I/usr/local/Trolltech/Qt-4.8.4/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.4/lib -lQtGui -L/usr/local/Trolltech/Qt-4.8.4/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		InterfaceWidget.cpp \
		MocpWatcher.cpp moc_InterfaceWidget.cpp \
		moc_MocpWatcher.cpp \
		qrc_pictures.cpp
OBJECTS       = main.o \
		InterfaceWidget.o \
		MocpWatcher.o \
		moc_InterfaceWidget.o \
		moc_MocpWatcher.o \
		qrc_pictures.o
DIST          = /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		MocpInterface.pro
QMAKE_TARGET  = MocpInterface
DESTDIR       = 
TARGET        = MocpInterface

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_InterfaceWidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MocpInterface.pro  /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ -o Makefile MocpInterface.pro
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ -o Makefile MocpInterface.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MocpInterface1.0.0 || $(MKDIR) .tmp/MocpInterface1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MocpInterface1.0.0/ && $(COPY_FILE) --parents InterfaceWidget.hpp MocpWatcher.hpp .tmp/MocpInterface1.0.0/ && $(COPY_FILE) --parents pictures.qrc .tmp/MocpInterface1.0.0/ && $(COPY_FILE) --parents main.cpp InterfaceWidget.cpp MocpWatcher.cpp .tmp/MocpInterface1.0.0/ && $(COPY_FILE) --parents InterfaceWidget.ui .tmp/MocpInterface1.0.0/ && (cd `dirname .tmp/MocpInterface1.0.0` && $(TAR) MocpInterface1.0.0.tar MocpInterface1.0.0 && $(COMPRESS) MocpInterface1.0.0.tar) && $(MOVE) `dirname .tmp/MocpInterface1.0.0`/MocpInterface1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MocpInterface1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_InterfaceWidget.cpp moc_MocpWatcher.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_InterfaceWidget.cpp moc_MocpWatcher.cpp
moc_InterfaceWidget.cpp: MocpWatcher.hpp \
		InterfaceWidget.hpp
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) InterfaceWidget.hpp -o moc_InterfaceWidget.cpp

moc_MocpWatcher.cpp: MocpWatcher.hpp
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) MocpWatcher.hpp -o moc_MocpWatcher.cpp

compiler_rcc_make_all: qrc_pictures.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_pictures.cpp
qrc_pictures.cpp: pictures.qrc \
		mocp_icon.png
	/usr/local/Trolltech/Qt-4.8.4/bin/rcc -name pictures pictures.qrc -o qrc_pictures.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_InterfaceWidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_InterfaceWidget.h
ui_InterfaceWidget.h: InterfaceWidget.ui
	/usr/local/Trolltech/Qt-4.8.4/bin/uic InterfaceWidget.ui -o ui_InterfaceWidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp InterfaceWidget.hpp \
		MocpWatcher.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

InterfaceWidget.o: InterfaceWidget.cpp InterfaceWidget.hpp \
		MocpWatcher.hpp \
		ui_InterfaceWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InterfaceWidget.o InterfaceWidget.cpp

MocpWatcher.o: MocpWatcher.cpp MocpWatcher.hpp \
		InterfaceWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MocpWatcher.o MocpWatcher.cpp

moc_InterfaceWidget.o: moc_InterfaceWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InterfaceWidget.o moc_InterfaceWidget.cpp

moc_MocpWatcher.o: moc_MocpWatcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MocpWatcher.o moc_MocpWatcher.cpp

qrc_pictures.o: qrc_pictures.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_pictures.o qrc_pictures.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

